litellm_settings:
  max_end_user_budget_id: "default_customer_budget"

general_settings:
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Id
      litellm_user_role: customer
    # - header_name: X-OpenWebUI-User-Email
    #   litellm_user_role: internal_user
